// Pesticide returned by GET /api/spray-reports/pesticides.
// Used to populate the dropdown in the worker spray-report form.
export interface Pesticide {
  PesticideId: number;
  Name: string;
  ActiveIngredient: string | null;
  Manufacturer: string | null;
  TargetPest: string | null;
  PreHarvestIntervalDays: number | null;
  ReEntryIntervalHours: number | null;
  PpeRequired: string | null;
  HazardLevel: string | null;
  VerificationStatus: 'verified' | 'unverified';
}

// Body sent to POST /api/spray-reports.
export interface CreateSprayReportRequest {
  zoneId: number;
  pesticideId: number;
  reportType: 'completed' | 'planned';
  plannedAtUtc?: string;
  notes?: string;
}

// One saved spray report (echoed back from the server after submit).
export interface SprayReport {
  SprayReportId: number;
  ZoneId: number;
  PesticideId: number;
  ReportedByUserId: number;
  Status: 'completed' | 'planned' | 'cancelled';
  PlannedAtUtc: string | null;
  CompletedAtUtc: string | null;
  Notes: string | null;
  RequiresApproval: boolean;
  CreatedAt: string;
}

// Safety warning generated by the backend after the report is saved.
// For 'verified' pesticides the dates are filled in; for 'unverified'
// pesticides they are null and `message` asks the worker to consult
// the official label.
export interface SafetyWarning {
  pesticideName: string;
  verificationStatus: 'verified' | 'unverified';
  requiresApproval: boolean;
  safeToReEnterAtUtc: string | null;
  safeToHarvestAtUtc: string | null;
  ppeRequired: string | null;
  hazardLevel: string | null;
  message: string;
}

// Combined response from POST /api/spray-reports.
export interface SprayReportSubmissionResponse {
  report: SprayReport;
  safetyWarning: SafetyWarning;
}

// US30: Manager spray alert created when a worker submits a spray report.
// Returned by GET /api/spray-reports/alerts (FarmManager only).
export interface SprayAlert {
  SprayAlertId: number;
  SprayReportId: number;
  ZoneId: number;
  ZoneCode: string;
  ZoneName: string;
  PesticideName: string | null;
  ReportedByUserId: number | null;
  ReportStatus: 'completed' | 'planned';
  Severity: 'high' | 'medium' | 'low';
  SafetyMessage: string;
  RequiresApproval: boolean;
  ReEntryIntervalHours: number | null;
  SafeToReEnterAtUtc: string | null;
  SafeToHarvestAtUtc: string | null;
  HazardLevel: string | null;
  PpeRequired: string | null;
  SprayedAtUtc: string | null;
  IsRead: boolean;
  CreatedAt: string;
}

// Per-zone spray status returned by GET /api/spray-reports/zone-map (US28).
export type ZoneSprayStatus =
  | 'safe'
  | 'unsafe'
  | 'requires_approval'
  | 'pending'
  | 'never_sprayed';

export interface ZoneSprayStatusData {
  zoneId: number;
  zoneCode: string;
  zoneName: string;
  sprayStatus: ZoneSprayStatus;
  lastCompletedAtUtc: string | null;
  pesticideName: string | null;
  safeToReEnterAtUtc: string | null;
  safeToHarvestAtUtc: string | null;
  requiresApproval: boolean;
  hazardLevel: string | null;
  ppeRequired: string | null;
  nextPlannedAtUtc: string | null;
}

// US32: Manager overdue spray alert — created by periodic scheduler when a zone
// has not been sprayed within DEFAULT_SPRAY_INTERVAL_DAYS (30 days).
// Separate from SprayAlert (US30) which is tied to a specific SprayReport.
export interface OverdueSprayAlert {
  OverdueAlertId:    number;
  ZoneId:            number;
  ZoneCode:          string;
  ZoneName:          string;
  LastSprayedAtUtc:  string | null;
  OverdueSinceUtc:   string;
  SprayIntervalDays: number;
  Severity:          'high' | 'medium' | 'low';
  Message:           string;
  IsRead:            boolean;
  IsResolved:        boolean;
  ResolvedAtUtc:     string | null;
  AssignedTaskId:    number | null;
  CreatedAt:         string;
}

// Body for POST /api/spray-reports/overdue-alerts/{id}/assign
export interface AssignOverdueAlertRequest {
  assignedToUserId: number;
  dueDate?: string;
}