"""
Chatbot request/response schemas.

Used by the visitor AI chatbot endpoint. These are plain API DTOs (simple
camelCase fields), not tied to any SQLAlchemy model — the chatbot is read-only
and never persists anything.
"""

from typing import Literal

from pydantic import BaseModel, Field


class ChatRequest(BaseModel):
    """A single question sent by the visitor to the chatbot."""

    message: str = Field(..., min_length=1, max_length=1000)


class ChatResponse(BaseModel):
    """The chatbot's reply.

    `source` indicates where the answer came from:
      - "db"       → grounded in internal data fetched from the database
      - "ai"       → a general recommendation generated by OpenAI
      - "fallback" → no matching data / service unavailable; safe canned reply
    """

    answer: str
    source: Literal["db", "ai", "fallback"]
