-- Table: Users
-- Description: System users (managers and employees)

-- | Column       | Type          | Nullable | Default           | Notes                        |
-- |--------------|---------------|----------|-------------------|------------------------------|
-- | UserId       | INT           | NO       | IDENTITY (auto)   | Primary Key                  |
-- | FullName     | NVARCHAR(100) | NO       |                   |                              |
-- | Email        | NVARCHAR(100) | NO       |                   | Unique                       |
-- | PasswordHash | NVARCHAR(255) | NO       |                   |                              |
-- | RoleId       | INT           | NO       |                   | FK -> Roles.RoleId           |
-- | IsActive     | BIT           | NO       | 1                 |                              |
-- | CreatedAt    | DATETIME2     | NO       | SYSUTCDATETIME()  |                              |
